In [13]:
import numpy as np 

In [15]:
print('get a custom list')
def special_calc(function_x, from_x, to_x, spread_x):
    return list(map(lambda x_var:eval(function_x.replace('x','x_var')), np.linspace(from_x,to_x,spread_x).tolist()))
print(special_calc('x**2', 1,31.622779,10))
ht_ls = special_calc('x**2', 1,31.622779,10)

get a custom list
[1.0, 19.382279205960998, 60.91899282384401, 125.61014085364903, 213.45572329537603, 324.4557401490251, 458.6101914145961, 615.9190770920891, 796.3823971815041, 1000.0001516828411]


In [7]:
list_var = [1.0, 4.0, 9.0, 16.0, 25.0, 36.0, 49.0, 64.0, 81.0, 100.0]
print(list_var)

[1.0, 4.0, 9.0, 16.0, 25.0, 36.0, 49.0, 64.0, 81.0, 100.0]


In [11]:
list_var = [1.0, 4.0, 9.0, 16.0, 25.0, 36.0, 49.0, 64.0, 81.0, 100.0]
print("slice list in half")
first_sliced_list_var = list_var[0:int(len(list_var)/2)]
print(first_sliced_list_var)
second_sliced_list_var = list_var[int(len(list_var)/2)::]
print(second_sliced_list_var)

slice list in half
[1.0, 4.0, 9.0, 16.0, 25.0]
[36.0, 49.0, 64.0, 81.0, 100.0]


In [9]:
list_var = [1.0, 4.0, 9.0, 16.0, 25.0, 36.0, 49.0, 64.0, 81.0, 100.0]
print("increase list with double of each values")
n_var = []
for i in list_var:
      n_var += [i*2]
list_var += n_var
list_var.sort()
print(list_var)

increase list with double of each values
[1.0, 2.0, 4.0, 8.0, 9.0, 16.0, 18.0, 25.0, 32.0, 36.0, 49.0, 50.0, 64.0, 72.0, 81.0, 98.0, 100.0, 128.0, 162.0, 200.0]


In [10]:
print("Sum and average of values:")
list_nrm = [20,14,16,19,20,19,15,20,20,19]
def get_average(list_nr):
    return ((sum(list_nr))/(len(list_nr)))
print(list_nrm)
print(sum(list_nrm), 'sum()')
print(len(list_nrm), 'len()')
print(get_average(list_nrm), 'get_average()')

Sum and average of values:
[20, 14, 16, 19, 20, 19, 15, 20, 20, 19]
182 sum()
10 len()
18.2 get_average()


In [14]:
matrix_var = np.eye(4).tolist()
print(type(matrix_var))
print(matrix_var)
matrix_var = np.eye(4)
print(type(matrix_var))
print(matrix_var)

<class 'list'>
[[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]
<class 'numpy.ndarray'>
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
print('defining list to array without numpy quick and easy')
ls_r=[[0]*6]*6
ls_r

defining list to array without numpy quick and easy


[[0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0]]

In [15]:
print('Unpacking lists')
list_packed_elements = [13,222,413,444]
a_1, b_2, c_3, d_4 = list_packed_elements
print(a_1, b_2, c_3, d_4, 'unpacked')
a_1, *middle_elements, d_4 = list_packed_elements
print(a_1, 'first element')
print(middle_elements, 'shortened from both ends')
print(d_4, 'last element')

Unpacking lists
13 222 413 444 unpacked
13 first element
[222, 413] shortened from both ends
444 last element


In [3]:
print('Splitting lists')
print([*'splitsome']) 
rand_str = 'splitsome'
newlist = [rand_str[i:i+3] for i in range(0, len(rand_str), 3)]
print(newlist) 

Splitting lists
['s', 'p', 'l', 'i', 't', 's', 'o', 'm', 'e']
['spl', 'its', 'ome']


In [8]:
print('# Compare lists')
u_ls_1 = ['3q1','2b2','3','b','c']
u_ls_2 = ['c', '3q1','2b2','a','4']
print('###########################')
print('list 1', u_ls_1)
print('list 2', u_ls_2)
print('###########################')
print('#-- elemment in list --#')
for i in u_ls_2:                        
    if i in u_ls_1:
        print(i, 'in list 1')
print('---------------------------')
for i in u_ls_1:
    if i in u_ls_2:
        print(i, 'in list 2')
print('#-- elemment not in list --#')
for i in u_ls_2:                        
    if i not in u_ls_1:
        print(i, 'not in list 1')
print('---------------------------')
for i in u_ls_1:
    if i not in u_ls_2:
        print(i, 'not in list 2')
print('###########################')

# Compare lists
###########################
list 1 ['3q1', '2b2', '3', 'b', 'c']
list 2 ['c', '3q1', '2b2', 'a', '4']
###########################
#-- elemment in list --#
c in list 1
3q1 in list 1
2b2 in list 1
---------------------------
3q1 in list 2
2b2 in list 2
c in list 2
#-- elemment not in list --#
a not in list 1
4 not in list 1
---------------------------
3 not in list 2
b not in list 2
###########################
